substitutions:
    zone_11: "Bonus Room"
    zone_12: "Upstairs Office"
    zone_13: "Kitchen"
    zone_14: "Master"
    zone_15: "Patio"
    zone_16: "Living Room"

esphome:
  name: monoprice-6ch-wt32-eth01
  platform: ESP32
  board: esp-wrover-kit
  libraries:
    - AsyncTCP-esphome

# Enable logging
logger:
  logs:
    monoprice-10761: DEBUG

# Enable Home Assistant API
api:
  password: ""

web_server:

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

ota:
  password: ""

  # wifi cannot be enabled with ethernet
  # wifi:
  #   ssid: !secret wifi_ssid
  #   password: !secret wifi_password
  # 
  #   # Enable fallback hotspot (captive portal) in case wifi connection fails
  #   ap:
  #     ssid: "Monoprice 6Ch Fallback Hotspot"
  #     password: !secret ap_password
  # 
  # captive_portal:

switch:
  - platform: restart
    name: "EspHome Restart"

sensor:
  - platform: uptime
    name: Uptime Sensor
    id: uptime_sensor
    update_interval: 15s

packages:
  sensors: !include { file: monoprice-6ch-sensors.yaml, vars: { input_1_name: "Sonos Port" } }
  zone11: !include { file: monoprice-6ch-zone.yaml, vars: { zone_name: "${zone_11}", zone_number: 11 } }
  zone12: !include { file: monoprice-6ch-zone.yaml, vars: { zone_name: "${zone_12}", zone_number: 12 } }
  zone13: !include { file: monoprice-6ch-zone.yaml, vars: { zone_name: "${zone_13}", zone_number: 13 } }
  zone14: !include { file: monoprice-6ch-zone.yaml, vars: { zone_name: "${zone_14}", zone_number: 14 } }
  zone15: !include { file: monoprice-6ch-zone.yaml, vars: { zone_name: "${zone_15}", zone_number: 15 } }
  zone16: !include { file: monoprice-6ch-zone.yaml, vars: { zone_name: "${zone_16}", zone_number: 16 } }